= George's TableTop Simulator Dreadball League
:toc: left

A casual Dreadball League to be played online in TableTop Simulator.

== League Rules

* The schedule will be determined ahead of the season.
  Every team will play every other team twice, once at home and once as visitor.

* Games will be played weekly at a time agreed upon between the players playing the game.
  The *DreadBall* Discord will be used for communication during a game.
  Allowances will be made for games to be made up the following week if neccessary.
  The week begins on Monday.

* Post game advancements will be done with opponent immediately after the played game.
  Updates to the team roster and standings will be done via pull request to the league site.
  The opponent will approve the pull request.

== League Differences

=== Teams
* Teams need to be unique within the league and will be assigned via <<team_draft, Team Draft>>
* Teams will be added to the league in roughly the original *Dreadball* Season order
** _The Red Planets_ and _Renton Rejects_ will be subbed in for the _Kovoss Kryptics_ and _Ro-Tek Brutes_
* Teams will continue to exist between seasons without resetting.

==== Team Draft
. Coaches determine funds for bidding.
  New coaches to the league start with 200 MC.
  Existing coaches that wish to sell their teams between seasons, take half the cash on hand from their existing team and update the team to reflect that.
. Coaches submit a blind bid based on their available cash for position in the draft.
. Coaches choose, in bid order, from the expansion teams and the sold teams from existing coaches.
. Any remaining money the coaches have is added to their new teams roster, and can be spent immediately.

=== Players
* MVPs will be added to the league in roughly the original *Dreadball* Season order
* Transfers
** Rookie transfers work as transfers do in the rules as listed.
** Experienced players can be traded between teams.
*** Trades do not need to be one to one or even between only two coaches.
*** Trades can be done anytime between games.
*** Standard transfer fees apply, if a player has three (four?) or more advancements use the MVP fee.
* Players can use the generic advancement table, their original teams advancements table, or the table from the team they are currently on.

=== Home Arena
In future seasons a team will be able to choose it's home arena.
Either the standard arena or the Azure Forest, and potentially any future *Galactic Cup* arenas that are published.
A fee will be required to change arenas between seasons.

== Important Links And Tools
* Dreadball Rules
** https://www.manticgames.com/games/uncategorised/dreadball-core-rules-and-team-stats/[Main Rules and Team Stats]
** https://www.manticgames.com/games/uncategorised/dreadball-faq-errata/[FAQ & Errata] (important changes from published rules are contained within)
** If you need the League Rules let me know
* Git
** https://github.com/Dreadball-TTS-League/georges-league[League Website Repo]
* AsciiDoc
** https://asciidoctor.org[Main Site]
** https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[Syntax Reference]
* TableTop Simulator
** https://store.steampowered.com/app/286160/Tabletop_Simulator/[Main Software]
** https://steamcommunity.com/sharedfiles/filedetails/?id=2101789056[Main Mod]
** https://steamcommunity.com/sharedfiles/filedetails/?id=2103951312[Ultimate Mod]
** https://www.dropbox.com/s/ygzhujj1xqbg8gs/Using%20Dreadball%202.docx?dl=0[Directions for using the Mod]
* https://discord.gg/4XvFYvw[Dreadball Discord]
